---

- name: bash existing check
  stat: 
    path: "{{ bash_bin }}"
  register: result
- block:
  - name: create tmp dir
    file: 
      path: "{{ tmp_dir }}"
      state: directory
      mode: 0755
  - name: download bash {{ version }}
    get_url: 
      url: "http://ftp.gnu.org/gnu/bash/bash-{{version}}.tar.gz"
      dest: "{{ tmp_dir }}/bash-{{version}}.tar.gz"
  - name: unarchive bash {{ version }}
    command:
      "tar -zxvf {{ tmp_dir }}/bash-{{version}}.tar.gz -C {{ tmp_dir }}/"
  - name: configure
    command: 
      chdir: "{{ tmp_dir }}/bash-{{version}}"
      cmd: ./configure
  - name: make
    make:
      chdir: "{{ tmp_dir }}/bash-{{version}}"
  - name: make install
    make:
      chdir: "{{ tmp_dir }}/bash-{{version}}"
      target: install
    become: yes
  - name: edit /etc/shells
    lineinfile:
      dest: /etc/shells
      line: "{{ bash_bin }}"
    become: yes
  - name: chsh
    command:
      "chsh -s {{ bash_bin }}"
  when: result.stat.exists == False
- name: remove tmp dir
  file:
    state: absent
    path: "{{ tmp_dir }}/"