---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
    - vars/vars.yml
  roles:
    - homebrew
    - homebrew_cask
    - geerlingguy.mas
    - dotfiles
    - vim
