- block:
  - name: check awscli
    command: "which aws"
    register: result
    check_mode: no
    changed_when: no
    failed_when: no

  - block:
    - name: download awscli installer
      get_url:
        url: https://awscli.amazonaws.com/AWSCLIV2.pkg
        dest: /tmp/AWSCLIV2.pkg
        validate_certs: no
      register: download

    - name: install awscli
      become: yes
      command: "installer -pkg {{ download.dest }} -target /"

    when: result.rc == 1

  - name: add completion to .bashrc
    lineinfile:
      path: ~/.bashrc
      line: complete -C aws_completer aws

  - name: delete awscli installer
    file:
      path: /tmp/AWSCLIV2.pkg
      state: absent

  tags:
    - awscli