---
- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Tap external Homebrew repositories
  homebrew_tap:
    tap: "{{ item }}"
    state: "present"
  with_items: "{{ homebrew_repositories }}"
  when: homebrew_repositories is defined

- name: Install Homebrew formulae
  homebrew:
    name: "{{ homebrew_formulae }}"
    state: "present"
  when: homebrew_formulae is defined
