homebrew_cask_formulae:
  - authy
  - alfred
  - aws-vault
  - bitwarden
  - clipy
  - docker
  - google-chrome
  - google-cloud-sdk
  - google-japanese-ime
  - iterm2
  - kindle
  - ngrok
  - notion
  - shiftit
  - skitch
  - slack
  - visual-studio-code
  - wireshark
