---
- name: Tap external Homebrew Cask repositories
  homebrew_tap:
    tap: "{{ item }}"
    state: "present"
  with_items: "{{ homebrew_cask_repositories }}"
  when: homebrew_cask_repositories is defined

- name: Install Homebrew Cask formulae
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_formulae }}" 
  when: homebrew_cask_formulae is defined